Dataset has 2 values:

*   comment - text
*   sentiment - categorical feature with 2 classes - target

In [20]:
from google.colab import drive
import os.path
drive.mount('/content/gdrive', force_remount=True)
data_set_path = '/content/gdrive/MyDrive/ML/HW13/'

Mounted at /content/gdrive


In [21]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer, TfidfVectorizer, HashingVectorizer
from sklearn.pipeline import Pipeline


df = pd.read_csv(data_set_path + 'IMDB Dataset.csv')

In [22]:
import torch
import torchtext
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder
from torchtext.data.functional import to_map_style_dataset
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader
from torchtext.data.functional import to_map_style_dataset


from torch.utils.data import Dataset

class IMDBDataset(Dataset):
    def __init__(self, dataframe):
        self.dataframe = dataframe

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, index):
        return self.dataframe.iloc[index]

# Label encoding
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(df['sentiment'])
df['sentiment'] = y_encoded


train_dataset, test_dataset = train_test_split(df, test_size=0.2, random_state=42)

from torchtext.data import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

tokenizer = get_tokenizer("basic_english")

def build_vocabulary(datasets):
    for dataset in datasets:
      for text in dataset['review']:
        yield tokenizer(text)

vocab = build_vocab_from_iterator(build_vocabulary([train_dataset, test_dataset]), min_freq=1, specials=["<UNK>"])
vocab.set_default_index(vocab["<UNK>"])
print("Vocabulary Len: {}".format(len(vocab)))
target_classes = ["Positive", "Negative"]

max_words = 25

def vectorize_batch(batch):
    #print(batch)
    X, Y = list(zip(*batch))
    X = [vocab(tokenizer(text)) for text in X]
    X = [tokens+([0]* (max_words-len(tokens))) if len(tokens) < max_words else tokens[:max_words] for tokens in X] ## Bringing all samples to max_words length.

    return torch.tensor(X, dtype=torch.int32), torch.tensor(Y) - 1 ## We have deducted 1 from target names to get

print(train_dataset)
test_loader  = DataLoader(IMDBDataset(test_dataset) , batch_size=1024, collate_fn=vectorize_batch, shuffle=True)
train_loader = DataLoader(IMDBDataset(train_dataset), batch_size=1024, collate_fn=vectorize_batch, shuffle=True)

train_features, train_labels = next(iter(train_loader))
print(f"Feature batch shape: {train_features.size()}")
print(f"Labels batch shape: {train_labels.size()}")

test_features, test_labels = next(iter(test_loader))
print(f"Feature batch shape: {test_features.size()}")
print(f"Labels batch shape: {test_labels.size()}")



Vocabulary Len: 147157
                                                  review  sentiment
39087  That's what I kept asking myself during the ma...          0
30893  I did not watch the entire movie. I could not ...          0
45278  A touching love story reminiscent of ‘In the M...          1
16398  This latter-day Fulci schlocker is a totally a...          0
13653  First of all, I firmly believe that Norwegian ...          0
...                                                  ...        ...
11284  `Shadow Magic' recaptures the joy and amazemen...          1
44732  I found this movie to be quite enjoyable and f...          1
38158  Avoid this one! It is a terrible movie. So wha...          0
860    This production was quite a surprise for me. I...          1
15795  This is a decent movie. Although little bit sh...          1

[40000 rows x 2 columns]
Feature batch shape: torch.Size([1024, 25])
Labels batch shape: torch.Size([1024])
Feature batch shape: torch.Size([1024, 25])
Labels b

In [23]:
from torch import nn
from torch.nn import functional as F

embed_len = 50
hidden_dim = 50
n_layers=1

class RNNClassifier(nn.Module):
    def __init__(self):
        super(RNNClassifier, self).__init__()
        self.embedding_layer = nn.Embedding(num_embeddings=len(vocab), embedding_dim=embed_len)
        self.rnn = nn.RNN(input_size=embed_len, hidden_size=hidden_dim, num_layers=n_layers, batch_first=True)
        self.linear = nn.Linear(hidden_dim, len(target_classes))

    def forward(self, X_batch):
        embeddings = self.embedding_layer(X_batch)
        output, hidden = self.rnn(embeddings, torch.randn(n_layers, len(X_batch), hidden_dim))
        return self.linear(output[:,-1])

rnn_classifier = RNNClassifier()

rnn_classifier

for layer in rnn_classifier.children():
    print("Layer : {}".format(layer))
    print("Parameters : ")
    for param in layer.parameters():
        print(param.shape)

out = rnn_classifier(torch.randint(0, len(vocab), (1024, max_words)))

out.shape

Layer : Embedding(147157, 50)
Parameters : 
torch.Size([147157, 50])
Layer : RNN(50, 50, batch_first=True)
Parameters : 
torch.Size([50, 50])
torch.Size([50, 50])
torch.Size([50])
torch.Size([50])
Layer : Linear(in_features=50, out_features=2, bias=True)
Parameters : 
torch.Size([2, 50])
torch.Size([2])


torch.Size([1024, 2])

In [24]:
from tqdm import tqdm
from sklearn.metrics import accuracy_score
import gc

def CalcValLossAndAccuracy(model, loss_fn, val_loader):
    with torch.no_grad():
        Y_shuffled, Y_preds, losses = [],[],[]
        for X, Y in val_loader:
            preds = model(X)
            Y = Y + 1
            loss = loss_fn(preds, Y)
            losses.append(loss.item())

            Y_shuffled.append(Y)
            Y_preds.append(preds.argmax(dim=-1))

        Y_shuffled = torch.cat(Y_shuffled)
        Y_preds = torch.cat(Y_preds)

        print("Valid Loss : {:.3f}".format(torch.tensor(losses).mean()))
        print("Valid Acc  : {:.3f}".format(accuracy_score(Y_shuffled.detach().numpy(), Y_preds.detach().numpy())))


def TrainModel(model, loss_fn, optimizer, train_loader, val_loader, epochs=10):
    for i in range(1, epochs+1):
        losses = []
        for X, Y in tqdm(train_loader):
            Y_preds = model(X)
            print('===========')
            Y = Y + 1
            print(Y)
            loss = loss_fn(Y_preds, Y)
            losses.append(loss.item())

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

        print("Train Loss : {:.3f}".format(torch.tensor(losses).mean()))
        CalcValLossAndAccuracy(model, loss_fn, val_loader)

In [25]:
from torch.optim import Adam

epochs = 15
learning_rate = 1e-3

loss_fn = nn.CrossEntropyLoss()
rnn_classifier = RNNClassifier()
optimizer = Adam(rnn_classifier.parameters(), lr=learning_rate)

print(train_loader)
print(type(train_loader))
print(len(train_loader))

TrainModel(rnn_classifier, loss_fn, optimizer, train_loader, test_loader, epochs)

<class 'torch.utils.data.dataloader.DataLoader'>
40


  2%|▎         | 1/40 [00:00<00:16,  2.31it/s]

tensor([0, 1, 0,  ..., 0, 0, 1])


  5%|▌         | 2/40 [00:00<00:15,  2.38it/s]

tensor([1, 1, 0,  ..., 0, 0, 1])


  8%|▊         | 3/40 [00:01<00:18,  2.01it/s]

tensor([1, 0, 1,  ..., 1, 1, 1])


 10%|█         | 4/40 [00:01<00:16,  2.13it/s]

tensor([1, 1, 1,  ..., 1, 1, 0])


 12%|█▎        | 5/40 [00:02<00:15,  2.22it/s]

tensor([1, 1, 1,  ..., 1, 0, 0])


 15%|█▌        | 6/40 [00:02<00:14,  2.27it/s]

tensor([0, 0, 1,  ..., 1, 1, 0])


 18%|█▊        | 7/40 [00:03<00:14,  2.34it/s]

tensor([0, 0, 0,  ..., 0, 0, 0])


 20%|██        | 8/40 [00:03<00:13,  2.36it/s]

tensor([1, 1, 0,  ..., 1, 0, 1])


 22%|██▎       | 9/40 [00:03<00:13,  2.38it/s]

tensor([1, 1, 0,  ..., 1, 0, 0])


 25%|██▌       | 10/40 [00:04<00:12,  2.39it/s]

tensor([1, 1, 1,  ..., 1, 0, 0])


 28%|██▊       | 11/40 [00:04<00:13,  2.20it/s]

tensor([1, 1, 0,  ..., 0, 1, 1])


 30%|███       | 12/40 [00:05<00:12,  2.27it/s]

tensor([1, 0, 0,  ..., 1, 1, 0])


 32%|███▎      | 13/40 [00:05<00:11,  2.32it/s]

tensor([1, 1, 1,  ..., 1, 0, 0])


 35%|███▌      | 14/40 [00:06<00:11,  2.33it/s]

tensor([0, 1, 0,  ..., 1, 1, 1])


 38%|███▊      | 15/40 [00:06<00:10,  2.37it/s]

tensor([1, 0, 1,  ..., 1, 0, 0])


 40%|████      | 16/40 [00:07<00:11,  2.15it/s]

tensor([1, 0, 0,  ..., 0, 0, 0])


 42%|████▎     | 17/40 [00:07<00:10,  2.23it/s]

tensor([0, 1, 1,  ..., 0, 0, 0])


 45%|████▌     | 18/40 [00:07<00:09,  2.30it/s]

tensor([1, 1, 0,  ..., 1, 0, 1])


 48%|████▊     | 19/40 [00:08<00:08,  2.37it/s]

tensor([0, 0, 0,  ..., 0, 1, 0])


 50%|█████     | 20/40 [00:08<00:08,  2.39it/s]

tensor([1, 0, 0,  ..., 0, 0, 1])


 52%|█████▎    | 21/40 [00:09<00:07,  2.41it/s]

tensor([1, 0, 0,  ..., 0, 0, 0])


 55%|█████▌    | 22/40 [00:09<00:07,  2.31it/s]

tensor([1, 0, 0,  ..., 1, 0, 1])


 57%|█████▊    | 23/40 [00:10<00:08,  2.02it/s]

tensor([1, 1, 0,  ..., 1, 0, 0])


 60%|██████    | 24/40 [00:11<00:09,  1.66it/s]

tensor([0, 0, 0,  ..., 0, 0, 0])


 62%|██████▎   | 25/40 [00:11<00:09,  1.62it/s]

tensor([1, 1, 1,  ..., 1, 1, 1])


 65%|██████▌   | 26/40 [00:12<00:08,  1.59it/s]

tensor([0, 0, 1,  ..., 1, 1, 0])


 68%|██████▊   | 27/40 [00:13<00:08,  1.57it/s]

tensor([1, 0, 0,  ..., 0, 1, 1])


 70%|███████   | 28/40 [00:13<00:07,  1.57it/s]

tensor([0, 0, 0,  ..., 1, 0, 1])


 72%|███████▎  | 29/40 [00:14<00:06,  1.74it/s]

tensor([0, 1, 1,  ..., 1, 0, 1])


 75%|███████▌  | 30/40 [00:14<00:05,  1.91it/s]

tensor([0, 0, 1,  ..., 1, 0, 1])


 78%|███████▊  | 31/40 [00:15<00:04,  1.87it/s]

tensor([0, 1, 0,  ..., 1, 1, 1])


 80%|████████  | 32/40 [00:15<00:03,  2.01it/s]

tensor([0, 1, 1,  ..., 1, 0, 1])


 82%|████████▎ | 33/40 [00:15<00:03,  2.13it/s]

tensor([0, 1, 0,  ..., 1, 0, 0])


 85%|████████▌ | 34/40 [00:16<00:02,  2.24it/s]

tensor([0, 1, 0,  ..., 1, 1, 0])


 88%|████████▊ | 35/40 [00:16<00:02,  2.32it/s]

tensor([1, 0, 1,  ..., 1, 0, 1])


 90%|█████████ | 36/40 [00:17<00:01,  2.35it/s]

tensor([0, 1, 0,  ..., 1, 0, 0])


 92%|█████████▎| 37/40 [00:17<00:01,  2.18it/s]

tensor([1, 1, 0,  ..., 1, 0, 0])


 95%|█████████▌| 38/40 [00:18<00:00,  2.22it/s]

tensor([1, 1, 0,  ..., 1, 1, 0])


 98%|█████████▊| 39/40 [00:18<00:00,  2.31it/s]

tensor([1, 0, 1,  ..., 1, 1, 1])
tensor([0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
        0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0])


100%|██████████| 40/40 [00:18<00:00,  2.15it/s]


Train Loss : 0.699
Valid Loss : 0.694
Valid Acc  : 0.515


  2%|▎         | 1/40 [00:00<00:15,  2.46it/s]

tensor([0, 0, 1,  ..., 1, 0, 1])


  5%|▌         | 2/40 [00:00<00:18,  2.02it/s]

tensor([0, 0, 0,  ..., 1, 1, 0])


  8%|▊         | 3/40 [00:01<00:16,  2.21it/s]

tensor([1, 1, 0,  ..., 1, 1, 1])


 10%|█         | 4/40 [00:01<00:15,  2.32it/s]

tensor([0, 1, 0,  ..., 0, 0, 0])


 12%|█▎        | 5/40 [00:02<00:14,  2.38it/s]

tensor([0, 1, 0,  ..., 0, 0, 1])


 15%|█▌        | 6/40 [00:02<00:16,  2.04it/s]

tensor([1, 1, 0,  ..., 1, 1, 1])


 18%|█▊        | 7/40 [00:03<00:17,  1.85it/s]

tensor([0, 1, 1,  ..., 1, 1, 1])


 20%|██        | 8/40 [00:04<00:18,  1.74it/s]

tensor([0, 0, 0,  ..., 1, 0, 0])


 22%|██▎       | 9/40 [00:04<00:18,  1.68it/s]

tensor([0, 0, 1,  ..., 0, 0, 0])


 25%|██▌       | 10/40 [00:05<00:19,  1.51it/s]

tensor([0, 1, 0,  ..., 0, 0, 1])


 28%|██▊       | 11/40 [00:06<00:19,  1.52it/s]

tensor([1, 0, 1,  ..., 1, 0, 0])


 30%|███       | 12/40 [00:06<00:17,  1.60it/s]

tensor([1, 0, 1,  ..., 1, 1, 1])


 32%|███▎      | 13/40 [00:07<00:15,  1.78it/s]

tensor([1, 0, 0,  ..., 1, 0, 1])


 35%|███▌      | 14/40 [00:07<00:13,  1.96it/s]

tensor([1, 1, 0,  ..., 0, 1, 1])


 38%|███▊      | 15/40 [00:08<00:13,  1.90it/s]

tensor([0, 0, 0,  ..., 0, 1, 1])


 40%|████      | 16/40 [00:08<00:11,  2.05it/s]

tensor([0, 0, 1,  ..., 1, 0, 0])


 42%|████▎     | 17/40 [00:08<00:10,  2.16it/s]

tensor([1, 0, 1,  ..., 1, 0, 0])


 45%|████▌     | 18/40 [00:09<00:09,  2.25it/s]

tensor([0, 1, 1,  ..., 0, 0, 1])


 48%|████▊     | 19/40 [00:09<00:09,  2.32it/s]

tensor([1, 1, 0,  ..., 1, 0, 0])


 50%|█████     | 20/40 [00:10<00:08,  2.37it/s]

tensor([1, 0, 0,  ..., 0, 1, 1])


 52%|█████▎    | 21/40 [00:10<00:07,  2.40it/s]

tensor([0, 1, 0,  ..., 0, 0, 0])


 55%|█████▌    | 22/40 [00:10<00:07,  2.42it/s]

tensor([0, 1, 1,  ..., 1, 0, 1])


 57%|█████▊    | 23/40 [00:11<00:07,  2.19it/s]

tensor([1, 0, 1,  ..., 1, 1, 0])


 60%|██████    | 24/40 [00:11<00:07,  2.26it/s]

tensor([1, 1, 1,  ..., 1, 0, 1])


 62%|██████▎   | 25/40 [00:12<00:06,  2.34it/s]

tensor([1, 1, 0,  ..., 1, 1, 0])


 65%|██████▌   | 26/40 [00:12<00:05,  2.39it/s]

tensor([1, 0, 1,  ..., 0, 0, 0])


 68%|██████▊   | 27/40 [00:13<00:05,  2.42it/s]

tensor([1, 1, 1,  ..., 0, 0, 1])


 70%|███████   | 28/40 [00:13<00:04,  2.43it/s]

tensor([1, 1, 1,  ..., 0, 0, 1])


 72%|███████▎  | 29/40 [00:13<00:04,  2.43it/s]

tensor([0, 0, 1,  ..., 0, 0, 0])


 75%|███████▌  | 30/40 [00:14<00:04,  2.20it/s]

tensor([0, 1, 1,  ..., 1, 1, 1])


 78%|███████▊  | 31/40 [00:14<00:04,  2.24it/s]

tensor([0, 0, 0,  ..., 0, 0, 1])


 80%|████████  | 32/40 [00:15<00:03,  2.32it/s]

tensor([1, 0, 1,  ..., 1, 0, 0])


 82%|████████▎ | 33/40 [00:15<00:02,  2.37it/s]

tensor([1, 0, 0,  ..., 1, 1, 1])


 85%|████████▌ | 34/40 [00:16<00:02,  2.38it/s]

tensor([0, 1, 1,  ..., 0, 0, 0])


 88%|████████▊ | 35/40 [00:16<00:02,  2.42it/s]

tensor([0, 0, 0,  ..., 0, 1, 1])


 90%|█████████ | 36/40 [00:17<00:02,  1.88it/s]

tensor([0, 1, 1,  ..., 0, 0, 1])


 92%|█████████▎| 37/40 [00:17<00:01,  1.77it/s]

tensor([1, 1, 0,  ..., 0, 1, 1])


 95%|█████████▌| 38/40 [00:18<00:01,  1.70it/s]

tensor([1, 0, 1,  ..., 1, 0, 1])


 98%|█████████▊| 39/40 [00:19<00:00,  1.64it/s]

tensor([0, 1, 1,  ..., 0, 0, 1])
tensor([1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
        0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0])


100%|██████████| 40/40 [00:19<00:00,  2.06it/s]


Train Loss : 0.690
Valid Loss : 0.693
Valid Acc  : 0.523


  2%|▎         | 1/40 [00:00<00:22,  1.76it/s]

tensor([1, 0, 0,  ..., 0, 1, 0])


  5%|▌         | 2/40 [00:00<00:17,  2.13it/s]

tensor([0, 0, 1,  ..., 1, 0, 0])


  8%|▊         | 3/40 [00:01<00:16,  2.25it/s]

tensor([0, 0, 0,  ..., 1, 1, 1])


 10%|█         | 4/40 [00:01<00:15,  2.38it/s]

tensor([1, 1, 0,  ..., 0, 1, 1])


 12%|█▎        | 5/40 [00:02<00:14,  2.41it/s]

tensor([0, 0, 1,  ..., 0, 0, 0])


 15%|█▌        | 6/40 [00:02<00:13,  2.45it/s]

tensor([1, 1, 1,  ..., 1, 0, 0])


 18%|█▊        | 7/40 [00:02<00:13,  2.47it/s]

tensor([0, 1, 0,  ..., 1, 1, 1])


 20%|██        | 8/40 [00:03<00:14,  2.21it/s]

tensor([1, 0, 1,  ..., 0, 1, 0])


 22%|██▎       | 9/40 [00:03<00:13,  2.31it/s]

tensor([0, 1, 0,  ..., 0, 1, 0])


 25%|██▌       | 10/40 [00:04<00:12,  2.33it/s]

tensor([0, 0, 0,  ..., 0, 0, 0])


 28%|██▊       | 11/40 [00:04<00:12,  2.38it/s]

tensor([1, 0, 1,  ..., 1, 1, 1])


 30%|███       | 12/40 [00:05<00:11,  2.43it/s]

tensor([1, 0, 0,  ..., 1, 1, 1])


 32%|███▎      | 13/40 [00:05<00:11,  2.39it/s]

tensor([1, 0, 0,  ..., 0, 1, 1])


 35%|███▌      | 14/40 [00:05<00:10,  2.42it/s]

tensor([1, 1, 0,  ..., 0, 0, 1])


 38%|███▊      | 15/40 [00:06<00:11,  2.19it/s]

tensor([1, 0, 0,  ..., 0, 0, 0])


 40%|████      | 16/40 [00:06<00:10,  2.29it/s]

tensor([1, 1, 1,  ..., 1, 0, 1])


 42%|████▎     | 17/40 [00:07<00:09,  2.36it/s]

tensor([1, 1, 0,  ..., 0, 0, 0])


 45%|████▌     | 18/40 [00:07<00:09,  2.39it/s]

tensor([1, 1, 1,  ..., 0, 1, 0])


 48%|████▊     | 19/40 [00:08<00:09,  2.22it/s]

tensor([1, 1, 1,  ..., 1, 0, 1])


 50%|█████     | 20/40 [00:08<00:10,  1.98it/s]

tensor([1, 1, 0,  ..., 1, 0, 1])


 52%|█████▎    | 21/40 [00:09<00:10,  1.83it/s]

tensor([1, 0, 0,  ..., 1, 0, 0])


 55%|█████▌    | 22/40 [00:10<00:11,  1.61it/s]

tensor([0, 1, 0,  ..., 1, 0, 1])


 57%|█████▊    | 23/40 [00:10<00:10,  1.60it/s]

tensor([0, 0, 0,  ..., 1, 1, 0])


 60%|██████    | 24/40 [00:11<00:10,  1.56it/s]

tensor([0, 0, 0,  ..., 1, 0, 1])


 62%|██████▎   | 25/40 [00:12<00:09,  1.56it/s]

tensor([1, 0, 1,  ..., 1, 0, 1])


 65%|██████▌   | 26/40 [00:12<00:07,  1.76it/s]

tensor([1, 0, 0,  ..., 0, 1, 1])


 68%|██████▊   | 27/40 [00:13<00:06,  1.92it/s]

tensor([0, 1, 0,  ..., 1, 0, 0])


 70%|███████   | 28/40 [00:13<00:06,  1.85it/s]

tensor([1, 1, 1,  ..., 1, 1, 0])


 72%|███████▎  | 29/40 [00:14<00:05,  1.99it/s]

tensor([1, 1, 0,  ..., 0, 1, 0])


 75%|███████▌  | 30/40 [00:14<00:04,  2.13it/s]

tensor([0, 1, 0,  ..., 1, 0, 0])


 78%|███████▊  | 31/40 [00:14<00:04,  2.22it/s]

tensor([0, 0, 0,  ..., 0, 0, 0])


 80%|████████  | 32/40 [00:15<00:03,  2.30it/s]

tensor([1, 1, 1,  ..., 1, 1, 1])


 82%|████████▎ | 33/40 [00:15<00:03,  2.32it/s]

tensor([0, 0, 0,  ..., 1, 1, 0])


 85%|████████▌ | 34/40 [00:16<00:02,  2.37it/s]

tensor([0, 0, 1,  ..., 1, 1, 1])


 88%|████████▊ | 35/40 [00:16<00:02,  2.18it/s]

tensor([1, 1, 0,  ..., 1, 0, 0])


 90%|█████████ | 36/40 [00:17<00:01,  2.26it/s]

tensor([0, 0, 1,  ..., 1, 1, 1])


 92%|█████████▎| 37/40 [00:17<00:01,  2.33it/s]

tensor([1, 0, 1,  ..., 1, 0, 0])


 95%|█████████▌| 38/40 [00:17<00:00,  2.36it/s]

tensor([0, 1, 0,  ..., 1, 0, 0])


 98%|█████████▊| 39/40 [00:18<00:00,  2.38it/s]

tensor([1, 1, 0,  ..., 0, 1, 1])
tensor([0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
        1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
        0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1])


100%|██████████| 40/40 [00:18<00:00,  2.18it/s]


Train Loss : 0.687
Valid Loss : 0.691
Valid Acc  : 0.536


  2%|▎         | 1/40 [00:00<00:15,  2.50it/s]

tensor([1, 0, 0,  ..., 1, 1, 0])


  5%|▌         | 2/40 [00:00<00:16,  2.25it/s]

tensor([1, 0, 0,  ..., 0, 0, 1])


  8%|▊         | 3/40 [00:01<00:20,  1.85it/s]

tensor([1, 1, 1,  ..., 0, 1, 0])


 10%|█         | 4/40 [00:02<00:20,  1.74it/s]

tensor([0, 0, 1,  ..., 0, 1, 1])


 12%|█▎        | 5/40 [00:02<00:21,  1.65it/s]

tensor([1, 1, 1,  ..., 0, 1, 1])


 15%|█▌        | 6/40 [00:03<00:23,  1.47it/s]

tensor([1, 0, 0,  ..., 1, 0, 0])


 18%|█▊        | 7/40 [00:04<00:21,  1.50it/s]

tensor([1, 1, 0,  ..., 1, 1, 0])


 20%|██        | 8/40 [00:04<00:21,  1.51it/s]

tensor([0, 0, 0,  ..., 1, 0, 0])


 22%|██▎       | 9/40 [00:05<00:18,  1.70it/s]

tensor([1, 0, 0,  ..., 0, 1, 1])


 25%|██▌       | 10/40 [00:05<00:15,  1.88it/s]

tensor([0, 0, 0,  ..., 0, 1, 0])


 28%|██▊       | 11/40 [00:06<00:14,  2.03it/s]

tensor([0, 1, 1,  ..., 0, 1, 1])


 30%|███       | 12/40 [00:06<00:13,  2.14it/s]

tensor([0, 0, 0,  ..., 1, 1, 0])


 32%|███▎      | 13/40 [00:07<00:13,  2.04it/s]

tensor([1, 0, 0,  ..., 0, 0, 1])


 35%|███▌      | 14/40 [00:07<00:12,  2.15it/s]

tensor([1, 0, 0,  ..., 1, 1, 0])


 38%|███▊      | 15/40 [00:07<00:11,  2.23it/s]

tensor([0, 1, 1,  ..., 0, 1, 1])


 40%|████      | 16/40 [00:08<00:10,  2.31it/s]

tensor([0, 0, 1,  ..., 1, 1, 0])


 42%|████▎     | 17/40 [00:08<00:09,  2.30it/s]

tensor([1, 0, 0,  ..., 1, 1, 1])


 45%|████▌     | 18/40 [00:09<00:09,  2.38it/s]

tensor([1, 0, 1,  ..., 1, 0, 1])


 48%|████▊     | 19/40 [00:09<00:08,  2.42it/s]

tensor([1, 0, 1,  ..., 0, 0, 0])


 50%|█████     | 20/40 [00:10<00:09,  2.19it/s]

tensor([1, 0, 0,  ..., 1, 1, 0])


 52%|█████▎    | 21/40 [00:10<00:08,  2.26it/s]

tensor([0, 1, 0,  ..., 1, 0, 0])


 55%|█████▌    | 22/40 [00:10<00:07,  2.32it/s]

tensor([0, 0, 1,  ..., 0, 1, 1])


 57%|█████▊    | 23/40 [00:11<00:07,  2.36it/s]

tensor([0, 1, 0,  ..., 0, 1, 1])


 60%|██████    | 24/40 [00:11<00:06,  2.38it/s]

tensor([0, 0, 1,  ..., 1, 0, 1])


 62%|██████▎   | 25/40 [00:12<00:06,  2.41it/s]

tensor([1, 1, 1,  ..., 1, 0, 0])


 65%|██████▌   | 26/40 [00:12<00:06,  2.18it/s]

tensor([0, 0, 0,  ..., 1, 0, 1])


 68%|██████▊   | 27/40 [00:13<00:05,  2.26it/s]

tensor([0, 1, 0,  ..., 1, 1, 1])


 70%|███████   | 28/40 [00:13<00:05,  2.32it/s]

tensor([1, 0, 1,  ..., 0, 0, 1])


 72%|███████▎  | 29/40 [00:13<00:04,  2.33it/s]

tensor([1, 0, 1,  ..., 1, 1, 0])


 75%|███████▌  | 30/40 [00:14<00:04,  2.38it/s]

tensor([0, 0, 0,  ..., 1, 0, 0])


 78%|███████▊  | 31/40 [00:14<00:03,  2.39it/s]

tensor([1, 0, 1,  ..., 0, 1, 0])


 80%|████████  | 32/40 [00:15<00:03,  2.29it/s]

tensor([0, 1, 0,  ..., 0, 1, 0])


 82%|████████▎ | 33/40 [00:15<00:03,  1.97it/s]

tensor([0, 0, 0,  ..., 1, 1, 0])


 85%|████████▌ | 34/40 [00:16<00:03,  1.65it/s]

tensor([1, 0, 0,  ..., 1, 1, 0])


 88%|████████▊ | 35/40 [00:17<00:03,  1.62it/s]

tensor([1, 0, 0,  ..., 0, 0, 0])


 90%|█████████ | 36/40 [00:18<00:02,  1.59it/s]

tensor([1, 0, 1,  ..., 1, 1, 0])


 92%|█████████▎| 37/40 [00:18<00:01,  1.58it/s]

tensor([0, 1, 1,  ..., 0, 0, 1])


 95%|█████████▌| 38/40 [00:19<00:01,  1.58it/s]

tensor([0, 0, 0,  ..., 1, 1, 1])


 98%|█████████▊| 39/40 [00:19<00:00,  1.75it/s]

tensor([1, 0, 0,  ..., 1, 0, 0])
tensor([0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
        1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0])


100%|██████████| 40/40 [00:19<00:00,  2.02it/s]


Train Loss : 0.678
Valid Loss : 0.676
Valid Acc  : 0.580


  2%|▎         | 1/40 [00:00<00:16,  2.43it/s]

tensor([0, 1, 0,  ..., 1, 0, 0])


  5%|▌         | 2/40 [00:00<00:15,  2.44it/s]

tensor([0, 1, 1,  ..., 0, 0, 1])


  8%|▊         | 3/40 [00:01<00:15,  2.43it/s]

tensor([1, 0, 1,  ..., 0, 0, 0])


 10%|█         | 4/40 [00:01<00:16,  2.12it/s]

tensor([0, 0, 0,  ..., 1, 0, 1])


 12%|█▎        | 5/40 [00:02<00:15,  2.24it/s]

tensor([0, 0, 0,  ..., 1, 0, 1])


 15%|█▌        | 6/40 [00:02<00:14,  2.33it/s]

tensor([0, 1, 0,  ..., 1, 1, 0])


 18%|█▊        | 7/40 [00:03<00:14,  2.35it/s]

tensor([0, 0, 1,  ..., 1, 0, 0])


 20%|██        | 8/40 [00:03<00:13,  2.36it/s]

tensor([1, 1, 0,  ..., 0, 1, 0])


 22%|██▎       | 9/40 [00:03<00:13,  2.38it/s]

tensor([1, 0, 0,  ..., 1, 0, 1])


 25%|██▌       | 10/40 [00:04<00:12,  2.40it/s]

tensor([1, 1, 0,  ..., 0, 1, 1])


 28%|██▊       | 11/40 [00:04<00:11,  2.43it/s]

tensor([1, 1, 1,  ..., 1, 0, 0])


 30%|███       | 12/40 [00:05<00:12,  2.21it/s]

tensor([0, 1, 1,  ..., 1, 0, 0])


 32%|███▎      | 13/40 [00:05<00:11,  2.29it/s]

tensor([1, 0, 1,  ..., 0, 0, 0])


 35%|███▌      | 14/40 [00:05<00:11,  2.36it/s]

tensor([0, 0, 0,  ..., 1, 0, 0])


 38%|███▊      | 15/40 [00:06<00:10,  2.34it/s]

tensor([1, 0, 1,  ..., 0, 0, 0])


 40%|████      | 16/40 [00:07<00:11,  2.05it/s]

tensor([0, 1, 0,  ..., 1, 1, 0])


 42%|████▎     | 17/40 [00:07<00:12,  1.82it/s]

tensor([1, 0, 1,  ..., 0, 1, 1])


 45%|████▌     | 18/40 [00:08<00:12,  1.72it/s]

tensor([1, 1, 0,  ..., 1, 1, 0])


 48%|████▊     | 19/40 [00:09<00:13,  1.53it/s]

tensor([0, 1, 1,  ..., 0, 1, 1])


 50%|█████     | 20/40 [00:09<00:13,  1.53it/s]

tensor([1, 1, 1,  ..., 0, 0, 1])


 52%|█████▎    | 21/40 [00:10<00:12,  1.52it/s]

tensor([0, 0, 1,  ..., 0, 0, 0])


 55%|█████▌    | 22/40 [00:10<00:10,  1.69it/s]

tensor([1, 1, 0,  ..., 1, 0, 1])


 57%|█████▊    | 23/40 [00:11<00:09,  1.86it/s]

tensor([0, 0, 1,  ..., 1, 0, 0])


 60%|██████    | 24/40 [00:11<00:07,  2.00it/s]

tensor([0, 1, 0,  ..., 0, 1, 0])


 62%|██████▎   | 25/40 [00:12<00:07,  1.94it/s]

tensor([1, 1, 0,  ..., 0, 0, 0])


 65%|██████▌   | 26/40 [00:12<00:06,  2.05it/s]

tensor([0, 1, 1,  ..., 0, 0, 0])


 68%|██████▊   | 27/40 [00:13<00:06,  2.16it/s]

tensor([1, 0, 1,  ..., 0, 1, 1])


 70%|███████   | 28/40 [00:13<00:05,  2.21it/s]

tensor([0, 1, 1,  ..., 0, 0, 1])


 72%|███████▎  | 29/40 [00:14<00:04,  2.31it/s]

tensor([0, 0, 0,  ..., 0, 0, 0])


 75%|███████▌  | 30/40 [00:14<00:04,  2.35it/s]

tensor([1, 0, 0,  ..., 0, 0, 0])


 78%|███████▊  | 31/40 [00:14<00:03,  2.38it/s]

tensor([0, 1, 1,  ..., 0, 0, 0])


 80%|████████  | 32/40 [00:15<00:03,  2.40it/s]

tensor([1, 0, 0,  ..., 1, 0, 1])


 82%|████████▎ | 33/40 [00:15<00:03,  2.14it/s]

tensor([1, 1, 1,  ..., 0, 1, 0])


 85%|████████▌ | 34/40 [00:16<00:02,  2.25it/s]

tensor([1, 0, 0,  ..., 1, 0, 0])


 88%|████████▊ | 35/40 [00:16<00:02,  2.29it/s]

tensor([0, 0, 1,  ..., 0, 0, 0])


 90%|█████████ | 36/40 [00:17<00:01,  2.32it/s]

tensor([0, 1, 0,  ..., 1, 1, 1])


 92%|█████████▎| 37/40 [00:17<00:01,  2.38it/s]

tensor([1, 0, 0,  ..., 0, 1, 0])


 95%|█████████▌| 38/40 [00:17<00:00,  2.39it/s]

tensor([0, 1, 0,  ..., 0, 0, 0])


100%|██████████| 40/40 [00:18<00:00,  2.16it/s]

tensor([1, 0, 1,  ..., 0, 0, 1])
tensor([1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
        1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
        0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0])


Train Loss : 0.659
Valid Loss : 0.668
Valid Acc  : 0.601


  2%|▎         | 1/40 [00:00<00:25,  1.53it/s]

tensor([1, 0, 1,  ..., 0, 1, 0])


  5%|▌         | 2/40 [00:01<00:25,  1.50it/s]

tensor([1, 1, 0,  ..., 0, 1, 0])


  8%|▊         | 3/40 [00:01<00:24,  1.52it/s]

tensor([0, 1, 0,  ..., 1, 1, 0])


 10%|█         | 4/40 [00:02<00:25,  1.40it/s]

tensor([0, 0, 0,  ..., 1, 0, 1])


 12%|█▎        | 5/40 [00:03<00:21,  1.67it/s]

tensor([0, 0, 1,  ..., 0, 1, 0])


 15%|█▌        | 6/40 [00:03<00:18,  1.88it/s]

tensor([1, 0, 0,  ..., 0, 1, 0])


 18%|█▊        | 7/40 [00:03<00:16,  2.03it/s]

tensor([1, 0, 1,  ..., 0, 1, 0])


 20%|██        | 8/40 [00:04<00:14,  2.15it/s]

tensor([0, 1, 1,  ..., 0, 1, 0])


 22%|██▎       | 9/40 [00:04<00:13,  2.24it/s]

tensor([0, 0, 1,  ..., 1, 1, 0])


 25%|██▌       | 10/40 [00:05<00:12,  2.32it/s]

tensor([0, 1, 1,  ..., 1, 0, 1])


 28%|██▊       | 11/40 [00:05<00:13,  2.13it/s]

tensor([0, 0, 0,  ..., 0, 1, 0])


 30%|███       | 12/40 [00:06<00:12,  2.23it/s]

tensor([1, 0, 0,  ..., 0, 1, 0])


 32%|███▎      | 13/40 [00:06<00:11,  2.30it/s]

tensor([1, 0, 0,  ..., 1, 1, 0])


 35%|███▌      | 14/40 [00:06<00:11,  2.34it/s]

tensor([0, 1, 1,  ..., 1, 1, 1])


 38%|███▊      | 15/40 [00:07<00:10,  2.38it/s]

tensor([0, 1, 0,  ..., 1, 1, 0])


 40%|████      | 16/40 [00:07<00:09,  2.41it/s]

tensor([0, 0, 1,  ..., 0, 0, 0])


 42%|████▎     | 17/40 [00:08<00:09,  2.44it/s]

tensor([0, 0, 1,  ..., 1, 1, 1])


 45%|████▌     | 18/40 [00:08<00:10,  2.20it/s]

tensor([0, 1, 0,  ..., 0, 0, 1])


 48%|████▊     | 19/40 [00:09<00:09,  2.26it/s]

tensor([0, 0, 0,  ..., 0, 0, 1])


 50%|█████     | 20/40 [00:09<00:08,  2.31it/s]

tensor([1, 1, 1,  ..., 0, 1, 0])


 52%|█████▎    | 21/40 [00:09<00:08,  2.33it/s]

tensor([0, 0, 0,  ..., 1, 1, 1])


 55%|█████▌    | 22/40 [00:10<00:07,  2.37it/s]

tensor([1, 1, 1,  ..., 0, 1, 1])


 57%|█████▊    | 23/40 [00:10<00:07,  2.38it/s]

tensor([0, 1, 1,  ..., 1, 1, 0])


 60%|██████    | 24/40 [00:11<00:07,  2.17it/s]

tensor([0, 1, 1,  ..., 0, 1, 1])


 62%|██████▎   | 25/40 [00:11<00:06,  2.25it/s]

tensor([1, 0, 0,  ..., 0, 0, 1])


 65%|██████▌   | 26/40 [00:12<00:06,  2.30it/s]

tensor([0, 1, 0,  ..., 1, 1, 1])


 68%|██████▊   | 27/40 [00:12<00:05,  2.35it/s]

tensor([0, 0, 1,  ..., 1, 1, 1])


 70%|███████   | 28/40 [00:13<00:05,  2.14it/s]

tensor([0, 0, 1,  ..., 1, 0, 0])


 72%|███████▎  | 29/40 [00:13<00:05,  1.91it/s]

tensor([0, 1, 0,  ..., 0, 0, 1])


 75%|███████▌  | 30/40 [00:14<00:05,  1.78it/s]

tensor([1, 0, 1,  ..., 0, 1, 0])


 78%|███████▊  | 31/40 [00:15<00:05,  1.72it/s]

tensor([1, 1, 0,  ..., 0, 0, 1])


 80%|████████  | 32/40 [00:15<00:05,  1.52it/s]

tensor([0, 0, 0,  ..., 0, 0, 1])


 82%|████████▎ | 33/40 [00:16<00:04,  1.51it/s]

tensor([1, 0, 0,  ..., 0, 1, 1])


 85%|████████▌ | 34/40 [00:17<00:03,  1.58it/s]

tensor([0, 0, 1,  ..., 0, 0, 1])


 88%|████████▊ | 35/40 [00:17<00:02,  1.76it/s]

tensor([1, 0, 1,  ..., 1, 1, 0])


 90%|█████████ | 36/40 [00:17<00:02,  1.93it/s]

tensor([1, 1, 0,  ..., 1, 1, 0])


 92%|█████████▎| 37/40 [00:18<00:01,  2.05it/s]

tensor([0, 1, 1,  ..., 1, 0, 0])


 95%|█████████▌| 38/40 [00:18<00:00,  2.17it/s]

tensor([1, 1, 0,  ..., 0, 1, 0])


 98%|█████████▊| 39/40 [00:19<00:00,  2.04it/s]

tensor([0, 0, 1,  ..., 1, 0, 1])
tensor([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
        1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
        0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1])


100%|██████████| 40/40 [00:19<00:00,  2.06it/s]


Train Loss : 0.636
Valid Loss : 0.650
Valid Acc  : 0.626


  2%|▎         | 1/40 [00:00<00:15,  2.58it/s]

tensor([1, 0, 0,  ..., 1, 0, 0])


  5%|▌         | 2/40 [00:00<00:14,  2.56it/s]

tensor([1, 1, 1,  ..., 1, 0, 0])


  8%|▊         | 3/40 [00:01<00:14,  2.49it/s]

tensor([0, 1, 0,  ..., 1, 0, 0])


 10%|█         | 4/40 [00:01<00:16,  2.19it/s]

tensor([1, 1, 0,  ..., 1, 0, 0])


 12%|█▎        | 5/40 [00:02<00:15,  2.26it/s]

tensor([1, 1, 1,  ..., 0, 0, 0])


 15%|█▌        | 6/40 [00:02<00:14,  2.36it/s]

tensor([0, 0, 1,  ..., 1, 1, 1])


 18%|█▊        | 7/40 [00:02<00:13,  2.38it/s]

tensor([0, 0, 1,  ..., 0, 0, 0])


 20%|██        | 8/40 [00:03<00:13,  2.40it/s]

tensor([0, 0, 1,  ..., 1, 0, 0])


 22%|██▎       | 9/40 [00:03<00:12,  2.44it/s]

tensor([1, 0, 0,  ..., 0, 0, 1])


 25%|██▌       | 10/40 [00:04<00:13,  2.19it/s]

tensor([0, 1, 1,  ..., 0, 0, 0])


 28%|██▊       | 11/40 [00:04<00:13,  2.15it/s]

tensor([0, 1, 1,  ..., 1, 1, 1])


 30%|███       | 12/40 [00:05<00:14,  1.95it/s]

tensor([1, 0, 1,  ..., 0, 0, 0])


 32%|███▎      | 13/40 [00:06<00:14,  1.82it/s]

tensor([0, 1, 0,  ..., 0, 1, 0])


 35%|███▌      | 14/40 [00:06<00:15,  1.73it/s]

tensor([0, 1, 0,  ..., 1, 0, 1])


 38%|███▊      | 15/40 [00:07<00:15,  1.66it/s]

tensor([1, 1, 1,  ..., 1, 1, 1])


 40%|████      | 16/40 [00:08<00:14,  1.62it/s]

tensor([1, 1, 0,  ..., 0, 0, 0])


 42%|████▎     | 17/40 [00:08<00:15,  1.47it/s]

tensor([1, 0, 1,  ..., 1, 0, 1])


 45%|████▌     | 18/40 [00:09<00:13,  1.63it/s]

tensor([0, 0, 0,  ..., 1, 1, 0])


 48%|████▊     | 19/40 [00:09<00:11,  1.83it/s]

tensor([1, 1, 1,  ..., 0, 1, 0])


 50%|█████     | 20/40 [00:10<00:10,  1.98it/s]

tensor([1, 0, 0,  ..., 1, 1, 0])


 52%|█████▎    | 21/40 [00:10<00:09,  2.10it/s]

tensor([0, 0, 0,  ..., 1, 1, 1])


 55%|█████▌    | 22/40 [00:10<00:08,  2.19it/s]

tensor([0, 1, 1,  ..., 1, 0, 1])


 57%|█████▊    | 23/40 [00:11<00:07,  2.26it/s]

tensor([1, 0, 0,  ..., 0, 0, 0])


 60%|██████    | 24/40 [00:11<00:07,  2.11it/s]

tensor([1, 1, 1,  ..., 1, 0, 0])


 62%|██████▎   | 25/40 [00:12<00:06,  2.19it/s]

tensor([0, 1, 1,  ..., 0, 1, 1])


 65%|██████▌   | 26/40 [00:12<00:06,  2.30it/s]

tensor([0, 1, 0,  ..., 1, 1, 1])


 68%|██████▊   | 27/40 [00:13<00:05,  2.36it/s]

tensor([0, 1, 1,  ..., 1, 1, 1])


 70%|███████   | 28/40 [00:13<00:05,  2.39it/s]

tensor([0, 1, 0,  ..., 0, 0, 1])


 72%|███████▎  | 29/40 [00:13<00:04,  2.39it/s]

tensor([1, 1, 1,  ..., 1, 0, 0])


 75%|███████▌  | 30/40 [00:14<00:04,  2.41it/s]

tensor([0, 0, 1,  ..., 0, 0, 1])


 78%|███████▊  | 31/40 [00:14<00:04,  2.19it/s]

tensor([0, 1, 0,  ..., 1, 1, 0])


 80%|████████  | 32/40 [00:15<00:03,  2.28it/s]

tensor([1, 0, 1,  ..., 1, 0, 0])


 82%|████████▎ | 33/40 [00:15<00:03,  2.32it/s]

tensor([0, 0, 1,  ..., 0, 0, 0])


 85%|████████▌ | 34/40 [00:16<00:02,  2.36it/s]

tensor([0, 0, 0,  ..., 1, 0, 1])


 88%|████████▊ | 35/40 [00:16<00:02,  2.41it/s]

tensor([0, 1, 1,  ..., 1, 1, 0])


 90%|█████████ | 36/40 [00:16<00:01,  2.41it/s]

tensor([0, 0, 0,  ..., 0, 1, 0])


 92%|█████████▎| 37/40 [00:17<00:01,  2.18it/s]

tensor([1, 1, 1,  ..., 1, 0, 0])


 95%|█████████▌| 38/40 [00:17<00:00,  2.26it/s]

tensor([0, 1, 0,  ..., 1, 0, 1])


 98%|█████████▊| 39/40 [00:18<00:00,  2.29it/s]

tensor([0, 1, 1,  ..., 0, 1, 1])
tensor([1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
        0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1])


100%|██████████| 40/40 [00:18<00:00,  2.18it/s]


Train Loss : 0.608
Valid Loss : 0.649
Valid Acc  : 0.641


  2%|▎         | 1/40 [00:00<00:15,  2.52it/s]

tensor([0, 1, 0,  ..., 1, 1, 1])


  5%|▌         | 2/40 [00:00<00:19,  1.99it/s]

tensor([1, 0, 0,  ..., 1, 0, 0])


  8%|▊         | 3/40 [00:01<00:16,  2.19it/s]

tensor([0, 0, 1,  ..., 1, 0, 1])


 10%|█         | 4/40 [00:01<00:15,  2.27it/s]

tensor([0, 1, 0,  ..., 0, 0, 0])


 12%|█▎        | 5/40 [00:02<00:14,  2.35it/s]

tensor([0, 0, 1,  ..., 0, 0, 0])


 15%|█▌        | 6/40 [00:02<00:14,  2.37it/s]

tensor([1, 1, 1,  ..., 1, 1, 0])


 18%|█▊        | 7/40 [00:03<00:13,  2.41it/s]

tensor([1, 1, 1,  ..., 1, 1, 1])


 20%|██        | 8/40 [00:03<00:13,  2.43it/s]

tensor([0, 0, 0,  ..., 0, 0, 1])


 22%|██▎       | 9/40 [00:03<00:14,  2.16it/s]

tensor([1, 0, 0,  ..., 0, 1, 0])


 25%|██▌       | 10/40 [00:04<00:13,  2.24it/s]

tensor([1, 1, 0,  ..., 1, 1, 1])


 28%|██▊       | 11/40 [00:04<00:12,  2.30it/s]

tensor([1, 0, 1,  ..., 0, 0, 1])


 30%|███       | 12/40 [00:05<00:11,  2.36it/s]

tensor([0, 0, 1,  ..., 0, 0, 0])


 32%|███▎      | 13/40 [00:05<00:11,  2.38it/s]

tensor([1, 0, 1,  ..., 1, 1, 0])


 35%|███▌      | 14/40 [00:06<00:10,  2.38it/s]

tensor([1, 1, 0,  ..., 1, 1, 1])


 38%|███▊      | 15/40 [00:06<00:10,  2.44it/s]

tensor([1, 0, 1,  ..., 1, 0, 0])


 40%|████      | 16/40 [00:06<00:10,  2.20it/s]

tensor([0, 0, 1,  ..., 0, 1, 0])


 42%|████▎     | 17/40 [00:07<00:10,  2.28it/s]

tensor([1, 0, 0,  ..., 1, 1, 0])


 45%|████▌     | 18/40 [00:07<00:09,  2.30it/s]

tensor([1, 1, 0,  ..., 0, 1, 0])


 48%|████▊     | 19/40 [00:08<00:09,  2.33it/s]

tensor([1, 1, 0,  ..., 1, 1, 1])


 50%|█████     | 20/40 [00:08<00:08,  2.36it/s]

tensor([0, 0, 0,  ..., 1, 1, 0])


 52%|█████▎    | 21/40 [00:09<00:08,  2.37it/s]

tensor([1, 1, 0,  ..., 1, 1, 0])


 55%|█████▌    | 22/40 [00:09<00:07,  2.39it/s]

tensor([0, 1, 1,  ..., 0, 1, 1])


 57%|█████▊    | 23/40 [00:10<00:07,  2.15it/s]

tensor([1, 0, 1,  ..., 1, 0, 0])


 60%|██████    | 24/40 [00:10<00:08,  1.95it/s]

tensor([1, 0, 0,  ..., 1, 0, 1])


 62%|██████▎   | 25/40 [00:11<00:08,  1.80it/s]

tensor([0, 0, 0,  ..., 0, 1, 0])


 65%|██████▌   | 26/40 [00:11<00:08,  1.71it/s]

tensor([1, 1, 1,  ..., 1, 1, 1])


 68%|██████▊   | 27/40 [00:12<00:07,  1.66it/s]

tensor([1, 0, 0,  ..., 0, 1, 1])


 70%|███████   | 28/40 [00:13<00:07,  1.60it/s]

tensor([1, 0, 1,  ..., 0, 1, 1])


 72%|███████▎  | 29/40 [00:13<00:07,  1.57it/s]

tensor([1, 0, 1,  ..., 0, 1, 0])


 75%|███████▌  | 30/40 [00:14<00:06,  1.54it/s]

tensor([0, 1, 1,  ..., 0, 1, 1])


 78%|███████▊  | 31/40 [00:15<00:05,  1.73it/s]

tensor([0, 1, 1,  ..., 0, 0, 1])


 80%|████████  | 32/40 [00:15<00:04,  1.91it/s]

tensor([1, 0, 0,  ..., 0, 0, 1])


 82%|████████▎ | 33/40 [00:15<00:03,  2.04it/s]

tensor([1, 1, 1,  ..., 0, 1, 0])


 85%|████████▌ | 34/40 [00:16<00:02,  2.13it/s]

tensor([1, 1, 1,  ..., 0, 1, 0])


 88%|████████▊ | 35/40 [00:16<00:02,  2.23it/s]

tensor([0, 0, 1,  ..., 1, 1, 1])


 90%|█████████ | 36/40 [00:17<00:01,  2.07it/s]

tensor([0, 0, 1,  ..., 1, 0, 0])


 92%|█████████▎| 37/40 [00:17<00:01,  2.18it/s]

tensor([1, 1, 1,  ..., 0, 0, 1])


 95%|█████████▌| 38/40 [00:18<00:00,  2.24it/s]

tensor([0, 0, 1,  ..., 0, 1, 0])


 98%|█████████▊| 39/40 [00:18<00:00,  2.33it/s]

tensor([0, 1, 0,  ..., 0, 0, 0])
tensor([1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
        1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0])


100%|██████████| 40/40 [00:18<00:00,  2.16it/s]


Train Loss : 0.580
Valid Loss : 0.632
Valid Acc  : 0.653


  2%|▎         | 1/40 [00:00<00:22,  1.74it/s]

tensor([1, 1, 0,  ..., 0, 1, 1])


  5%|▌         | 2/40 [00:00<00:18,  2.10it/s]

tensor([0, 0, 0,  ..., 0, 1, 0])


  8%|▊         | 3/40 [00:01<00:16,  2.23it/s]

tensor([1, 0, 1,  ..., 1, 1, 0])


 10%|█         | 4/40 [00:01<00:15,  2.27it/s]

tensor([0, 0, 1,  ..., 0, 1, 0])


 12%|█▎        | 5/40 [00:02<00:14,  2.35it/s]

tensor([1, 0, 1,  ..., 1, 1, 1])


 15%|█▌        | 6/40 [00:02<00:14,  2.37it/s]

tensor([0, 1, 1,  ..., 1, 1, 1])


 18%|█▊        | 7/40 [00:03<00:15,  2.16it/s]

tensor([0, 0, 1,  ..., 0, 0, 1])


 20%|██        | 8/40 [00:03<00:16,  1.90it/s]

tensor([0, 0, 0,  ..., 0, 1, 1])


 22%|██▎       | 9/40 [00:04<00:19,  1.61it/s]

tensor([1, 1, 1,  ..., 0, 0, 0])


 25%|██▌       | 10/40 [00:05<00:19,  1.57it/s]

tensor([1, 0, 0,  ..., 0, 1, 0])


 28%|██▊       | 11/40 [00:06<00:18,  1.55it/s]

tensor([0, 1, 0,  ..., 0, 0, 0])


 30%|███       | 12/40 [00:06<00:18,  1.53it/s]

tensor([0, 0, 0,  ..., 0, 0, 0])


 32%|███▎      | 13/40 [00:07<00:17,  1.55it/s]

tensor([1, 0, 1,  ..., 0, 1, 1])


 35%|███▌      | 14/40 [00:07<00:14,  1.75it/s]

tensor([1, 0, 0,  ..., 0, 1, 0])


 38%|███▊      | 15/40 [00:08<00:14,  1.76it/s]

tensor([1, 0, 1,  ..., 0, 1, 1])


 40%|████      | 16/40 [00:08<00:12,  1.93it/s]

tensor([0, 1, 1,  ..., 0, 1, 1])


 42%|████▎     | 17/40 [00:09<00:11,  2.05it/s]

tensor([1, 1, 1,  ..., 0, 0, 1])


 45%|████▌     | 18/40 [00:09<00:10,  2.17it/s]

tensor([1, 1, 0,  ..., 0, 0, 1])


 48%|████▊     | 19/40 [00:09<00:09,  2.24it/s]

tensor([1, 0, 0,  ..., 1, 0, 0])


 50%|█████     | 20/40 [00:10<00:08,  2.31it/s]

tensor([0, 0, 0,  ..., 0, 1, 0])


 52%|█████▎    | 21/40 [00:10<00:08,  2.36it/s]

tensor([1, 0, 1,  ..., 1, 0, 1])


 55%|█████▌    | 22/40 [00:11<00:08,  2.15it/s]

tensor([1, 1, 1,  ..., 0, 1, 0])


 57%|█████▊    | 23/40 [00:11<00:07,  2.25it/s]

tensor([0, 0, 1,  ..., 0, 0, 0])


 60%|██████    | 24/40 [00:12<00:06,  2.30it/s]

tensor([0, 1, 0,  ..., 0, 0, 0])


 62%|██████▎   | 25/40 [00:12<00:06,  2.33it/s]

tensor([0, 0, 1,  ..., 1, 0, 1])


 65%|██████▌   | 26/40 [00:12<00:05,  2.35it/s]

tensor([1, 1, 1,  ..., 1, 1, 1])


 68%|██████▊   | 27/40 [00:13<00:05,  2.38it/s]

tensor([0, 0, 0,  ..., 1, 0, 1])


 70%|███████   | 28/40 [00:13<00:04,  2.42it/s]

tensor([0, 1, 1,  ..., 0, 1, 1])


 72%|███████▎  | 29/40 [00:14<00:04,  2.43it/s]

tensor([0, 1, 0,  ..., 1, 0, 1])


 75%|███████▌  | 30/40 [00:14<00:04,  2.20it/s]

tensor([0, 1, 0,  ..., 0, 0, 0])


 78%|███████▊  | 31/40 [00:15<00:03,  2.26it/s]

tensor([1, 1, 1,  ..., 0, 0, 1])


 80%|████████  | 32/40 [00:15<00:03,  2.32it/s]

tensor([0, 1, 1,  ..., 0, 1, 1])


 82%|████████▎ | 33/40 [00:15<00:02,  2.38it/s]

tensor([0, 1, 1,  ..., 1, 0, 1])


 85%|████████▌ | 34/40 [00:16<00:02,  2.39it/s]

tensor([1, 0, 0,  ..., 0, 0, 1])


 88%|████████▊ | 35/40 [00:16<00:02,  2.15it/s]

tensor([1, 0, 0,  ..., 1, 1, 0])


 90%|█████████ | 36/40 [00:17<00:01,  2.15it/s]

tensor([1, 1, 0,  ..., 1, 1, 0])


 92%|█████████▎| 37/40 [00:17<00:01,  1.93it/s]

tensor([1, 0, 0,  ..., 1, 1, 0])


 95%|█████████▌| 38/40 [00:18<00:01,  1.78it/s]

tensor([0, 1, 1,  ..., 0, 0, 0])


 98%|█████████▊| 39/40 [00:19<00:00,  1.68it/s]

tensor([0, 0, 1,  ..., 1, 1, 1])
tensor([0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
        1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
        1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1])


100%|██████████| 40/40 [00:19<00:00,  2.05it/s]


Train Loss : 0.555
Valid Loss : 0.635
Valid Acc  : 0.665


  2%|▎         | 1/40 [00:00<00:15,  2.48it/s]

tensor([1, 1, 0,  ..., 0, 0, 0])


  5%|▌         | 2/40 [00:00<00:15,  2.46it/s]

tensor([1, 1, 1,  ..., 0, 0, 1])


  8%|▊         | 3/40 [00:01<00:15,  2.45it/s]

tensor([0, 1, 0,  ..., 0, 0, 1])


 10%|█         | 4/40 [00:01<00:14,  2.45it/s]

tensor([1, 1, 0,  ..., 1, 0, 0])


 12%|█▎        | 5/40 [00:02<00:14,  2.40it/s]

tensor([1, 0, 1,  ..., 0, 1, 1])


 15%|█▌        | 6/40 [00:02<00:13,  2.45it/s]

tensor([1, 1, 1,  ..., 1, 1, 0])


 18%|█▊        | 7/40 [00:02<00:13,  2.43it/s]

tensor([1, 1, 0,  ..., 1, 0, 1])


 20%|██        | 8/40 [00:03<00:14,  2.19it/s]

tensor([1, 0, 1,  ..., 0, 1, 0])


 22%|██▎       | 9/40 [00:03<00:13,  2.27it/s]

tensor([0, 0, 1,  ..., 0, 1, 0])


 25%|██▌       | 10/40 [00:04<00:12,  2.31it/s]

tensor([1, 1, 1,  ..., 1, 1, 1])


 28%|██▊       | 11/40 [00:04<00:12,  2.36it/s]

tensor([1, 1, 1,  ..., 1, 0, 1])


 30%|███       | 12/40 [00:05<00:11,  2.37it/s]

tensor([1, 0, 0,  ..., 1, 1, 0])


 32%|███▎      | 13/40 [00:05<00:11,  2.43it/s]

tensor([1, 1, 1,  ..., 1, 0, 1])


 35%|███▌      | 14/40 [00:06<00:12,  2.16it/s]

tensor([0, 1, 0,  ..., 1, 1, 0])


 38%|███▊      | 15/40 [00:06<00:11,  2.24it/s]

tensor([0, 1, 0,  ..., 0, 1, 1])


 40%|████      | 16/40 [00:06<00:10,  2.28it/s]

tensor([1, 0, 0,  ..., 1, 0, 1])


 42%|████▎     | 17/40 [00:07<00:09,  2.33it/s]

tensor([0, 1, 1,  ..., 1, 1, 1])


 45%|████▌     | 18/40 [00:07<00:09,  2.36it/s]

tensor([1, 0, 0,  ..., 1, 0, 0])


 48%|████▊     | 19/40 [00:08<00:08,  2.38it/s]

tensor([0, 0, 0,  ..., 1, 1, 0])


 50%|█████     | 20/40 [00:08<00:09,  2.05it/s]

tensor([0, 1, 1,  ..., 0, 1, 0])


 52%|█████▎    | 21/40 [00:09<00:11,  1.68it/s]

tensor([0, 1, 1,  ..., 0, 1, 0])


 55%|█████▌    | 22/40 [00:10<00:11,  1.62it/s]

tensor([0, 0, 0,  ..., 0, 1, 0])


 57%|█████▊    | 23/40 [00:10<00:10,  1.59it/s]

tensor([1, 1, 1,  ..., 0, 0, 0])


 60%|██████    | 24/40 [00:11<00:10,  1.56it/s]

tensor([1, 0, 1,  ..., 1, 1, 0])


 62%|██████▎   | 25/40 [00:12<00:09,  1.56it/s]

tensor([0, 0, 0,  ..., 1, 1, 0])


 65%|██████▌   | 26/40 [00:12<00:08,  1.65it/s]

tensor([0, 0, 1,  ..., 0, 0, 0])


 68%|██████▊   | 27/40 [00:13<00:07,  1.83it/s]

tensor([0, 1, 0,  ..., 0, 1, 1])


 70%|███████   | 28/40 [00:13<00:06,  1.80it/s]

tensor([0, 0, 1,  ..., 0, 0, 0])


 72%|███████▎  | 29/40 [00:14<00:05,  1.95it/s]

tensor([0, 1, 0,  ..., 0, 0, 1])


 75%|███████▌  | 30/40 [00:14<00:04,  2.07it/s]

tensor([0, 0, 0,  ..., 0, 1, 1])


 78%|███████▊  | 31/40 [00:14<00:04,  2.18it/s]

tensor([1, 1, 1,  ..., 1, 0, 0])


 80%|████████  | 32/40 [00:15<00:03,  2.25it/s]

tensor([1, 1, 0,  ..., 1, 1, 1])


 82%|████████▎ | 33/40 [00:15<00:03,  2.31it/s]

tensor([1, 1, 1,  ..., 0, 1, 1])


 85%|████████▌ | 34/40 [00:16<00:02,  2.36it/s]

tensor([1, 0, 1,  ..., 1, 1, 0])


 88%|████████▊ | 35/40 [00:16<00:02,  2.13it/s]

tensor([1, 1, 1,  ..., 1, 0, 0])


 90%|█████████ | 36/40 [00:17<00:01,  2.21it/s]

tensor([0, 1, 1,  ..., 1, 0, 0])


 92%|█████████▎| 37/40 [00:17<00:01,  2.25it/s]

tensor([0, 1, 1,  ..., 1, 1, 0])


 95%|█████████▌| 38/40 [00:18<00:00,  2.29it/s]

tensor([1, 1, 0,  ..., 0, 1, 0])


 98%|█████████▊| 39/40 [00:18<00:00,  2.35it/s]

tensor([1, 1, 1,  ..., 0, 1, 0])
tensor([0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
        0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
        1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0])


100%|██████████| 40/40 [00:18<00:00,  2.16it/s]


Train Loss : 0.528
Valid Loss : 0.625
Valid Acc  : 0.676


  2%|▎         | 1/40 [00:00<00:15,  2.48it/s]

tensor([0, 0, 1,  ..., 0, 1, 1])


  5%|▌         | 2/40 [00:00<00:16,  2.37it/s]

tensor([0, 0, 0,  ..., 1, 1, 0])


  8%|▊         | 3/40 [00:01<00:19,  1.92it/s]

tensor([1, 1, 1,  ..., 0, 0, 0])


 10%|█         | 4/40 [00:02<00:20,  1.73it/s]

tensor([0, 0, 1,  ..., 1, 1, 1])


 12%|█▎        | 5/40 [00:02<00:21,  1.66it/s]

tensor([0, 1, 1,  ..., 1, 1, 1])


 15%|█▌        | 6/40 [00:03<00:21,  1.61it/s]

tensor([1, 1, 0,  ..., 0, 0, 0])


 18%|█▊        | 7/40 [00:04<00:20,  1.57it/s]

tensor([1, 1, 0,  ..., 1, 1, 1])


 20%|██        | 8/40 [00:04<00:22,  1.43it/s]

tensor([0, 0, 0,  ..., 0, 0, 0])


 22%|██▎       | 9/40 [00:05<00:19,  1.57it/s]

tensor([1, 1, 0,  ..., 1, 1, 1])


 25%|██▌       | 10/40 [00:05<00:17,  1.76it/s]

tensor([0, 0, 0,  ..., 0, 1, 1])


 28%|██▊       | 11/40 [00:06<00:15,  1.90it/s]

tensor([0, 0, 0,  ..., 1, 0, 1])


 30%|███       | 12/40 [00:06<00:13,  2.03it/s]

tensor([1, 1, 0,  ..., 0, 1, 0])


 32%|███▎      | 13/40 [00:07<00:12,  2.14it/s]

tensor([0, 0, 0,  ..., 1, 1, 0])


 35%|███▌      | 14/40 [00:07<00:12,  2.03it/s]

tensor([0, 1, 1,  ..., 1, 1, 0])


 38%|███▊      | 15/40 [00:08<00:11,  2.13it/s]

tensor([0, 0, 0,  ..., 1, 1, 1])


 40%|████      | 16/40 [00:08<00:10,  2.21it/s]

tensor([1, 1, 0,  ..., 0, 0, 0])


 42%|████▎     | 17/40 [00:08<00:10,  2.27it/s]

tensor([0, 0, 0,  ..., 0, 0, 0])


 45%|████▌     | 18/40 [00:09<00:09,  2.31it/s]

tensor([0, 1, 1,  ..., 1, 1, 1])


 48%|████▊     | 19/40 [00:09<00:08,  2.38it/s]

tensor([1, 0, 1,  ..., 0, 0, 1])


 50%|█████     | 20/40 [00:10<00:08,  2.39it/s]

tensor([1, 1, 1,  ..., 0, 1, 0])


 52%|█████▎    | 21/40 [00:10<00:08,  2.16it/s]

tensor([0, 0, 1,  ..., 0, 1, 0])


 55%|█████▌    | 22/40 [00:11<00:08,  2.23it/s]

tensor([0, 0, 0,  ..., 0, 1, 1])


 57%|█████▊    | 23/40 [00:11<00:07,  2.27it/s]

tensor([0, 0, 1,  ..., 1, 0, 0])


 60%|██████    | 24/40 [00:11<00:06,  2.33it/s]

tensor([0, 1, 1,  ..., 0, 1, 0])


 62%|██████▎   | 25/40 [00:12<00:06,  2.37it/s]

tensor([0, 1, 1,  ..., 0, 0, 1])


 65%|██████▌   | 26/40 [00:12<00:05,  2.38it/s]

tensor([1, 1, 1,  ..., 0, 0, 1])


 68%|██████▊   | 27/40 [00:13<00:05,  2.43it/s]

tensor([1, 1, 1,  ..., 0, 0, 1])


 70%|███████   | 28/40 [00:13<00:04,  2.43it/s]

tensor([0, 1, 1,  ..., 0, 1, 0])


 72%|███████▎  | 29/40 [00:14<00:05,  2.19it/s]

tensor([1, 0, 0,  ..., 1, 0, 1])


 75%|███████▌  | 30/40 [00:14<00:04,  2.24it/s]

tensor([1, 0, 0,  ..., 1, 1, 0])


 78%|███████▊  | 31/40 [00:14<00:03,  2.28it/s]

tensor([1, 0, 0,  ..., 1, 1, 0])


 80%|████████  | 32/40 [00:15<00:03,  2.17it/s]

tensor([1, 1, 0,  ..., 1, 1, 0])


 82%|████████▎ | 33/40 [00:16<00:03,  1.93it/s]

tensor([1, 1, 1,  ..., 1, 0, 1])


 85%|████████▌ | 34/40 [00:16<00:03,  1.78it/s]

tensor([1, 1, 1,  ..., 1, 1, 0])


 88%|████████▊ | 35/40 [00:17<00:03,  1.57it/s]

tensor([1, 0, 1,  ..., 0, 0, 1])


 90%|█████████ | 36/40 [00:18<00:02,  1.56it/s]

tensor([1, 1, 0,  ..., 1, 1, 1])


 92%|█████████▎| 37/40 [00:18<00:01,  1.54it/s]

tensor([1, 1, 0,  ..., 0, 0, 1])


 95%|█████████▌| 38/40 [00:19<00:01,  1.54it/s]

tensor([0, 1, 0,  ..., 1, 1, 1])


 98%|█████████▊| 39/40 [00:19<00:00,  1.73it/s]

tensor([1, 0, 1,  ..., 0, 0, 1])
tensor([0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
        0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1])


100%|██████████| 40/40 [00:20<00:00,  1.99it/s]


Train Loss : 0.507
Valid Loss : 0.630
Valid Acc  : 0.681


  2%|▎         | 1/40 [00:00<00:15,  2.54it/s]

tensor([1, 1, 1,  ..., 0, 1, 1])


  5%|▌         | 2/40 [00:00<00:15,  2.48it/s]

tensor([0, 0, 0,  ..., 0, 1, 0])


  8%|▊         | 3/40 [00:01<00:15,  2.46it/s]

tensor([1, 0, 1,  ..., 1, 1, 1])


 10%|█         | 4/40 [00:01<00:14,  2.42it/s]

tensor([0, 1, 1,  ..., 1, 1, 0])


 12%|█▎        | 5/40 [00:02<00:14,  2.44it/s]

tensor([0, 0, 0,  ..., 1, 1, 0])


 15%|█▌        | 6/40 [00:02<00:15,  2.16it/s]

tensor([1, 0, 1,  ..., 0, 1, 1])


 18%|█▊        | 7/40 [00:03<00:14,  2.27it/s]

tensor([1, 0, 1,  ..., 1, 0, 0])


 20%|██        | 8/40 [00:03<00:13,  2.32it/s]

tensor([0, 1, 1,  ..., 0, 0, 1])


 22%|██▎       | 9/40 [00:03<00:13,  2.37it/s]

tensor([0, 1, 0,  ..., 1, 1, 1])


 25%|██▌       | 10/40 [00:04<00:12,  2.40it/s]

tensor([1, 0, 1,  ..., 1, 0, 0])


 28%|██▊       | 11/40 [00:04<00:12,  2.40it/s]

tensor([0, 1, 0,  ..., 0, 0, 1])


 30%|███       | 12/40 [00:05<00:11,  2.45it/s]

tensor([0, 0, 1,  ..., 1, 1, 0])


 32%|███▎      | 13/40 [00:05<00:11,  2.42it/s]

tensor([1, 1, 1,  ..., 1, 1, 1])


 35%|███▌      | 14/40 [00:06<00:11,  2.18it/s]

tensor([0, 1, 1,  ..., 1, 0, 1])


 38%|███▊      | 15/40 [00:06<00:11,  2.24it/s]

tensor([1, 1, 1,  ..., 1, 0, 0])


 40%|████      | 16/40 [00:07<00:12,  1.98it/s]

tensor([0, 1, 0,  ..., 0, 0, 1])


 42%|████▎     | 17/40 [00:07<00:12,  1.83it/s]

tensor([0, 0, 1,  ..., 1, 1, 0])


 45%|████▌     | 18/40 [00:08<00:12,  1.74it/s]

tensor([1, 1, 1,  ..., 0, 1, 1])


 48%|████▊     | 19/40 [00:09<00:14,  1.50it/s]

tensor([0, 1, 0,  ..., 1, 0, 1])


 50%|█████     | 20/40 [00:09<00:13,  1.51it/s]

tensor([1, 1, 1,  ..., 1, 1, 1])


 52%|█████▎    | 21/40 [00:10<00:12,  1.52it/s]

tensor([1, 0, 0,  ..., 0, 0, 1])


 55%|█████▌    | 22/40 [00:11<00:10,  1.64it/s]

tensor([0, 0, 0,  ..., 0, 1, 0])


 57%|█████▊    | 23/40 [00:11<00:09,  1.82it/s]

tensor([1, 0, 1,  ..., 0, 1, 1])


 60%|██████    | 24/40 [00:11<00:08,  1.94it/s]

tensor([0, 1, 1,  ..., 0, 1, 0])


 62%|██████▎   | 25/40 [00:12<00:07,  2.05it/s]

tensor([0, 1, 1,  ..., 0, 1, 0])


 65%|██████▌   | 26/40 [00:12<00:06,  2.16it/s]

tensor([1, 1, 1,  ..., 1, 0, 1])


 68%|██████▊   | 27/40 [00:13<00:06,  2.03it/s]

tensor([1, 1, 1,  ..., 0, 1, 0])


 70%|███████   | 28/40 [00:13<00:05,  2.15it/s]

tensor([0, 1, 1,  ..., 1, 1, 0])


 72%|███████▎  | 29/40 [00:14<00:04,  2.21it/s]

tensor([0, 1, 1,  ..., 1, 0, 0])


 75%|███████▌  | 30/40 [00:14<00:04,  2.30it/s]

tensor([0, 0, 0,  ..., 0, 1, 0])


 78%|███████▊  | 31/40 [00:14<00:03,  2.34it/s]

tensor([1, 0, 1,  ..., 0, 0, 0])


 80%|████████  | 32/40 [00:15<00:03,  2.40it/s]

tensor([0, 1, 0,  ..., 1, 0, 1])


 82%|████████▎ | 33/40 [00:15<00:02,  2.42it/s]

tensor([1, 1, 1,  ..., 1, 0, 1])


 85%|████████▌ | 34/40 [00:16<00:02,  2.20it/s]

tensor([0, 0, 0,  ..., 0, 0, 0])


 88%|████████▊ | 35/40 [00:16<00:02,  2.27it/s]

tensor([1, 1, 1,  ..., 1, 1, 0])


 90%|█████████ | 36/40 [00:17<00:01,  2.31it/s]

tensor([0, 0, 0,  ..., 1, 0, 0])


 92%|█████████▎| 37/40 [00:17<00:01,  2.37it/s]

tensor([0, 0, 0,  ..., 1, 1, 1])


 95%|█████████▌| 38/40 [00:17<00:00,  2.40it/s]

tensor([1, 0, 0,  ..., 0, 1, 0])


 98%|█████████▊| 39/40 [00:18<00:00,  2.42it/s]

tensor([1, 1, 1,  ..., 1, 1, 0])
tensor([0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
        1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0])


100%|██████████| 40/40 [00:18<00:00,  2.17it/s]


Train Loss : 0.482
Valid Loss : 0.638
Valid Acc  : 0.683


  2%|▎         | 1/40 [00:00<00:25,  1.54it/s]

tensor([0, 1, 0,  ..., 1, 1, 1])


  5%|▌         | 2/40 [00:01<00:25,  1.51it/s]

tensor([0, 1, 0,  ..., 1, 1, 0])


  8%|▊         | 3/40 [00:01<00:24,  1.51it/s]

tensor([1, 0, 0,  ..., 0, 0, 0])


 10%|█         | 4/40 [00:02<00:23,  1.53it/s]

tensor([0, 0, 0,  ..., 0, 1, 1])


 12%|█▎        | 5/40 [00:03<00:21,  1.64it/s]

tensor([1, 0, 1,  ..., 0, 1, 0])


 15%|█▌        | 6/40 [00:03<00:20,  1.68it/s]

tensor([1, 1, 0,  ..., 1, 0, 0])


 18%|█▊        | 7/40 [00:04<00:17,  1.89it/s]

tensor([1, 1, 0,  ..., 1, 1, 1])


 20%|██        | 8/40 [00:04<00:15,  2.03it/s]

tensor([1, 1, 0,  ..., 1, 1, 1])


 22%|██▎       | 9/40 [00:04<00:14,  2.15it/s]

tensor([1, 0, 0,  ..., 0, 0, 1])


 25%|██▌       | 10/40 [00:05<00:13,  2.23it/s]

tensor([1, 0, 1,  ..., 1, 1, 0])


 28%|██▊       | 11/40 [00:05<00:12,  2.32it/s]

tensor([1, 0, 0,  ..., 0, 1, 0])


 30%|███       | 12/40 [00:06<00:11,  2.35it/s]

tensor([0, 1, 0,  ..., 1, 0, 0])


 32%|███▎      | 13/40 [00:06<00:11,  2.36it/s]

tensor([1, 1, 0,  ..., 1, 1, 0])


 35%|███▌      | 14/40 [00:07<00:12,  2.14it/s]

tensor([0, 0, 0,  ..., 0, 0, 0])


 38%|███▊      | 15/40 [00:07<00:11,  2.17it/s]

tensor([1, 1, 0,  ..., 1, 0, 1])


 40%|████      | 16/40 [00:07<00:10,  2.25it/s]

tensor([1, 0, 1,  ..., 1, 0, 0])


 42%|████▎     | 17/40 [00:08<00:10,  2.30it/s]

tensor([1, 0, 1,  ..., 0, 1, 0])


 45%|████▌     | 18/40 [00:08<00:09,  2.35it/s]

tensor([1, 0, 0,  ..., 0, 0, 0])


 48%|████▊     | 19/40 [00:09<00:08,  2.40it/s]

tensor([1, 0, 1,  ..., 0, 0, 1])


 50%|█████     | 20/40 [00:09<00:09,  2.16it/s]

tensor([1, 1, 1,  ..., 0, 0, 0])


 52%|█████▎    | 21/40 [00:10<00:08,  2.25it/s]

tensor([0, 1, 1,  ..., 1, 1, 0])


 55%|█████▌    | 22/40 [00:10<00:07,  2.30it/s]

tensor([1, 0, 0,  ..., 1, 0, 1])


 57%|█████▊    | 23/40 [00:10<00:07,  2.34it/s]

tensor([1, 1, 1,  ..., 1, 0, 0])


 60%|██████    | 24/40 [00:11<00:06,  2.38it/s]

tensor([0, 1, 1,  ..., 0, 0, 1])


 62%|██████▎   | 25/40 [00:11<00:06,  2.43it/s]

tensor([1, 0, 0,  ..., 1, 0, 1])


 65%|██████▌   | 26/40 [00:12<00:05,  2.45it/s]

tensor([1, 0, 1,  ..., 1, 0, 0])


 68%|██████▊   | 27/40 [00:12<00:05,  2.21it/s]

tensor([1, 1, 1,  ..., 0, 0, 0])


 70%|███████   | 28/40 [00:13<00:05,  2.08it/s]

tensor([1, 1, 1,  ..., 1, 1, 0])


 72%|███████▎  | 29/40 [00:13<00:05,  1.85it/s]

tensor([0, 0, 0,  ..., 0, 1, 1])


 75%|███████▌  | 30/40 [00:14<00:05,  1.75it/s]

tensor([0, 0, 0,  ..., 1, 0, 0])


 78%|███████▊  | 31/40 [00:15<00:05,  1.70it/s]

tensor([0, 0, 0,  ..., 0, 1, 0])


 80%|████████  | 32/40 [00:15<00:04,  1.65it/s]

tensor([1, 1, 0,  ..., 1, 1, 1])


 82%|████████▎ | 33/40 [00:16<00:04,  1.62it/s]

tensor([1, 0, 0,  ..., 0, 1, 0])


 85%|████████▌ | 34/40 [00:17<00:04,  1.46it/s]

tensor([0, 1, 0,  ..., 0, 1, 1])


 88%|████████▊ | 35/40 [00:17<00:03,  1.64it/s]

tensor([1, 0, 0,  ..., 0, 0, 1])


 90%|█████████ | 36/40 [00:18<00:02,  1.83it/s]

tensor([1, 1, 1,  ..., 0, 1, 0])


 92%|█████████▎| 37/40 [00:18<00:01,  1.97it/s]

tensor([1, 0, 1,  ..., 1, 0, 1])


 95%|█████████▌| 38/40 [00:19<00:00,  2.07it/s]

tensor([1, 0, 1,  ..., 1, 1, 1])


 98%|█████████▊| 39/40 [00:19<00:00,  2.16it/s]

tensor([1, 0, 1,  ..., 1, 0, 1])
tensor([0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
        0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
        0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1])


100%|██████████| 40/40 [00:19<00:00,  2.04it/s]


Train Loss : 0.460
Valid Loss : 0.619
Valid Acc  : 0.688


  2%|▎         | 1/40 [00:00<00:14,  2.61it/s]

tensor([0, 1, 1,  ..., 0, 1, 0])


  5%|▌         | 2/40 [00:00<00:15,  2.50it/s]

tensor([1, 0, 0,  ..., 0, 0, 1])


  8%|▊         | 3/40 [00:01<00:15,  2.46it/s]

tensor([1, 0, 0,  ..., 0, 1, 1])


 10%|█         | 4/40 [00:01<00:16,  2.13it/s]

tensor([1, 0, 1,  ..., 1, 0, 0])


 12%|█▎        | 5/40 [00:02<00:15,  2.21it/s]

tensor([1, 1, 1,  ..., 0, 0, 1])


 15%|█▌        | 6/40 [00:02<00:14,  2.31it/s]

tensor([1, 0, 0,  ..., 0, 0, 0])


 18%|█▊        | 7/40 [00:03<00:14,  2.33it/s]

tensor([0, 0, 1,  ..., 1, 0, 0])


 20%|██        | 8/40 [00:03<00:13,  2.36it/s]

tensor([1, 0, 1,  ..., 0, 0, 0])


 22%|██▎       | 9/40 [00:03<00:12,  2.39it/s]

tensor([0, 0, 1,  ..., 0, 1, 1])


 25%|██▌       | 10/40 [00:04<00:12,  2.39it/s]

tensor([0, 0, 0,  ..., 0, 1, 0])


 28%|██▊       | 11/40 [00:04<00:14,  2.05it/s]

tensor([1, 1, 0,  ..., 1, 1, 0])


 30%|███       | 12/40 [00:05<00:14,  1.87it/s]

tensor([1, 0, 1,  ..., 0, 1, 1])


 32%|███▎      | 13/40 [00:06<00:15,  1.76it/s]

tensor([0, 0, 0,  ..., 0, 0, 1])


 35%|███▌      | 14/40 [00:06<00:15,  1.67it/s]

tensor([0, 1, 1,  ..., 0, 0, 0])


 38%|███▊      | 15/40 [00:07<00:15,  1.63it/s]

tensor([0, 0, 0,  ..., 0, 1, 0])


 40%|████      | 16/40 [00:08<00:14,  1.61it/s]

tensor([0, 0, 1,  ..., 1, 0, 0])


 42%|████▎     | 17/40 [00:08<00:14,  1.57it/s]

tensor([0, 1, 0,  ..., 1, 1, 0])


 45%|████▌     | 18/40 [00:09<00:14,  1.57it/s]

tensor([0, 0, 1,  ..., 0, 0, 0])


 48%|████▊     | 19/40 [00:09<00:11,  1.76it/s]

tensor([0, 1, 1,  ..., 1, 0, 0])


 50%|█████     | 20/40 [00:10<00:10,  1.91it/s]

tensor([1, 0, 0,  ..., 0, 1, 0])


 52%|█████▎    | 21/40 [00:10<00:09,  2.02it/s]

tensor([0, 1, 1,  ..., 0, 1, 0])


 55%|█████▌    | 22/40 [00:11<00:08,  2.12it/s]

tensor([1, 1, 1,  ..., 1, 1, 0])


 57%|█████▊    | 23/40 [00:11<00:07,  2.21it/s]

tensor([0, 0, 1,  ..., 1, 0, 1])


 60%|██████    | 24/40 [00:11<00:07,  2.26it/s]

tensor([1, 0, 1,  ..., 1, 1, 0])


 62%|██████▎   | 25/40 [00:12<00:07,  2.11it/s]

tensor([0, 0, 0,  ..., 1, 1, 0])


 65%|██████▌   | 26/40 [00:12<00:06,  2.19it/s]

tensor([0, 1, 1,  ..., 0, 0, 1])


 68%|██████▊   | 27/40 [00:13<00:05,  2.24it/s]

tensor([1, 0, 0,  ..., 0, 0, 0])


 70%|███████   | 28/40 [00:13<00:05,  2.29it/s]

tensor([0, 0, 0,  ..., 0, 0, 1])


 72%|███████▎  | 29/40 [00:14<00:04,  2.35it/s]

tensor([0, 0, 0,  ..., 1, 1, 0])


 75%|███████▌  | 30/40 [00:14<00:04,  2.36it/s]

tensor([0, 0, 0,  ..., 0, 0, 0])


 78%|███████▊  | 31/40 [00:14<00:03,  2.39it/s]

tensor([1, 0, 0,  ..., 1, 1, 1])


 80%|████████  | 32/40 [00:15<00:03,  2.40it/s]

tensor([1, 1, 0,  ..., 1, 1, 0])


 82%|████████▎ | 33/40 [00:15<00:03,  2.17it/s]

tensor([1, 1, 0,  ..., 0, 1, 0])


 85%|████████▌ | 34/40 [00:16<00:02,  2.26it/s]

tensor([0, 1, 1,  ..., 0, 1, 0])


 88%|████████▊ | 35/40 [00:16<00:02,  2.30it/s]

tensor([0, 1, 0,  ..., 0, 1, 1])


 90%|█████████ | 36/40 [00:17<00:01,  2.34it/s]

tensor([0, 1, 1,  ..., 1, 0, 0])


 92%|█████████▎| 37/40 [00:17<00:01,  2.37it/s]

tensor([0, 1, 1,  ..., 0, 0, 0])


 95%|█████████▌| 38/40 [00:18<00:00,  2.38it/s]

tensor([1, 1, 0,  ..., 0, 0, 0])


 98%|█████████▊| 39/40 [00:18<00:00,  2.17it/s]

tensor([0, 1, 0,  ..., 0, 0, 1])
tensor([1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
        0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1])


100%|██████████| 40/40 [00:18<00:00,  2.14it/s]


Train Loss : 0.439
Valid Loss : 0.632
Valid Acc  : 0.695


  2%|▎         | 1/40 [00:00<00:16,  2.40it/s]

tensor([1, 0, 1,  ..., 0, 1, 0])


  5%|▌         | 2/40 [00:00<00:15,  2.44it/s]

tensor([0, 1, 1,  ..., 1, 1, 0])


  8%|▊         | 3/40 [00:01<00:17,  2.09it/s]

tensor([1, 1, 1,  ..., 0, 1, 1])


 10%|█         | 4/40 [00:01<00:16,  2.22it/s]

tensor([1, 0, 0,  ..., 0, 1, 1])


 12%|█▎        | 5/40 [00:02<00:15,  2.31it/s]

tensor([0, 0, 0,  ..., 0, 1, 1])


 15%|█▌        | 6/40 [00:02<00:14,  2.32it/s]

tensor([0, 0, 1,  ..., 0, 1, 0])


 18%|█▊        | 7/40 [00:03<00:14,  2.33it/s]

tensor([1, 1, 0,  ..., 0, 1, 1])


 20%|██        | 8/40 [00:03<00:13,  2.35it/s]

tensor([0, 1, 1,  ..., 0, 0, 0])


 22%|██▎       | 9/40 [00:03<00:13,  2.36it/s]

tensor([0, 0, 1,  ..., 1, 1, 0])


 25%|██▌       | 10/40 [00:04<00:14,  2.14it/s]

tensor([0, 1, 0,  ..., 1, 1, 0])


 28%|██▊       | 11/40 [00:04<00:13,  2.21it/s]

tensor([1, 1, 0,  ..., 1, 0, 0])


 30%|███       | 12/40 [00:05<00:12,  2.27it/s]

tensor([0, 1, 1,  ..., 0, 1, 0])


 32%|███▎      | 13/40 [00:05<00:11,  2.31it/s]

tensor([0, 0, 0,  ..., 0, 0, 1])


 35%|███▌      | 14/40 [00:06<00:11,  2.36it/s]

tensor([1, 1, 1,  ..., 0, 0, 1])


 38%|███▊      | 15/40 [00:06<00:10,  2.40it/s]

tensor([1, 1, 0,  ..., 0, 0, 1])


 40%|████      | 16/40 [00:06<00:10,  2.38it/s]

tensor([0, 0, 1,  ..., 1, 0, 1])


 42%|████▎     | 17/40 [00:07<00:10,  2.17it/s]

tensor([1, 0, 1,  ..., 1, 0, 0])


 45%|████▌     | 18/40 [00:07<00:09,  2.24it/s]

tensor([0, 0, 1,  ..., 1, 1, 0])


 48%|████▊     | 19/40 [00:08<00:09,  2.29it/s]

tensor([1, 0, 1,  ..., 1, 1, 0])


 50%|█████     | 20/40 [00:08<00:08,  2.30it/s]

tensor([1, 0, 1,  ..., 1, 1, 1])


 52%|█████▎    | 21/40 [00:09<00:08,  2.36it/s]

tensor([0, 0, 1,  ..., 0, 1, 1])


 55%|█████▌    | 22/40 [00:09<00:07,  2.37it/s]

tensor([1, 1, 0,  ..., 1, 0, 0])


 57%|█████▊    | 23/40 [00:10<00:07,  2.24it/s]

tensor([0, 0, 0,  ..., 0, 1, 1])


 60%|██████    | 24/40 [00:10<00:09,  1.76it/s]

tensor([1, 0, 0,  ..., 0, 1, 0])


 62%|██████▎   | 25/40 [00:11<00:08,  1.70it/s]

tensor([0, 0, 0,  ..., 1, 1, 0])


 65%|██████▌   | 26/40 [00:12<00:08,  1.65it/s]

tensor([1, 0, 0,  ..., 0, 1, 1])


 68%|██████▊   | 27/40 [00:12<00:08,  1.61it/s]

tensor([1, 1, 1,  ..., 0, 1, 1])


 70%|███████   | 28/40 [00:13<00:07,  1.59it/s]

tensor([1, 1, 1,  ..., 0, 1, 0])


 72%|███████▎  | 29/40 [00:14<00:07,  1.57it/s]

tensor([1, 1, 0,  ..., 1, 1, 0])


 75%|███████▌  | 30/40 [00:14<00:05,  1.74it/s]

tensor([0, 1, 1,  ..., 1, 0, 0])


 78%|███████▊  | 31/40 [00:15<00:05,  1.75it/s]

tensor([0, 1, 1,  ..., 1, 0, 0])


 80%|████████  | 32/40 [00:15<00:04,  1.92it/s]

tensor([1, 1, 1,  ..., 0, 0, 1])


 82%|████████▎ | 33/40 [00:15<00:03,  2.03it/s]

tensor([1, 1, 1,  ..., 1, 0, 1])


 85%|████████▌ | 34/40 [00:16<00:02,  2.13it/s]

tensor([0, 0, 1,  ..., 0, 1, 1])


 88%|████████▊ | 35/40 [00:16<00:02,  2.21it/s]

tensor([1, 1, 1,  ..., 1, 0, 1])


 90%|█████████ | 36/40 [00:17<00:01,  2.26it/s]

tensor([0, 0, 0,  ..., 1, 0, 1])


 92%|█████████▎| 37/40 [00:17<00:01,  2.07it/s]

tensor([1, 0, 0,  ..., 0, 0, 0])


 95%|█████████▌| 38/40 [00:18<00:00,  2.16it/s]

tensor([0, 0, 1,  ..., 0, 0, 1])


 98%|█████████▊| 39/40 [00:18<00:00,  2.25it/s]

tensor([0, 1, 0,  ..., 1, 0, 0])
tensor([1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0])


100%|██████████| 40/40 [00:18<00:00,  2.13it/s]


Train Loss : 0.418
Valid Loss : 0.646
Valid Acc  : 0.695
